### ISSUE TITLE
SwiftDSSocket deinit crash

### ISSUE THREAD

**Issue by advoryanskiy** [csujedihy/SwiftDSSocket#1]
Sometimes it crashed on deinit.

Example code:
```
self.serverSocket = SwiftDSSocket(delegate: self, delegateQueue: DispatchQueue.global(qos: .default), type: .tcp)
try self.serverSocket.accept(onPort: 12345)

// ...
// do something with the server socket
// ...

self.serverSocket.disconnect()
self.serverSocket = nil
```

Sometimes it crashes when call `self.serverSocket = nil`.

**Comment by advoryanskiy** [comment]
I found that it's a concurrency issue. When we are deallocating socket right after `.disconnect()` method call, async disconnection sometimes doesn't have enough time to be done.

So, I added `DispatchGroup` for async blocks in `.disconnect()` methods, changed self to strong reference in the async blocks and added waiting on the dispatch group in `deinit` method to be sure that the disconnection will be done .

**Comment by csujedihy** [comment]
Thank you! I think only `disconnect()` needs to be fixed because async disconnect has a callback and user should call `self.serverSocket = nil` in the callback. How do you think about it?

**Comment by advoryanskiy** [comment]
Yes, you are right. I've updated my pull request.

**Comment by csujedihy** [comment]
Merged

**Comment by advoryanskiy** [comment]
@csujedihy, when you will have a time, may you please create a new release with the fix?

**Comment by csujedihy** [comment]
Yes. I will do it by today. Did you find any problems of this framework?

**Comment by advoryanskiy** [comment]
Thank you! I didn't find any other issues with the framework. I'm using the framework in my app, so if I'll find any problem, I'll post an issue and create a pull request.

**Comment by csujedihy** [comment]
Thank you! I have released the latest one.

**Comment by advoryanskiy** [comment]
Great! Thank you.
